[[plugins]]
  package = "@netlify/plugin-lighthouse"
  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.98
    # accessibility = 0.98
    # best-practices = 0.98
    # seo = 0.9
    #pwa = 0.5
[[headers]]
  for = "/*"
  [headers.values]
  	cache-control = '''
	    max-age=0,
      no-cache,
      no-store,
      must-revalidate'''
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src data: 'unsafe-inline'  https:; script-src data: 'unsafe-inline'  https: blob:; style-src data: 'unsafe-inline' https:; img-src data: https: blob:; font-src data: https:; connect-src https: wss: blob:; media-src https: blob:; object-src https:; child-src https: data: blob:; form-action https:; block-all-mixed-content"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy= "geolocation=(), microphone=()"

[[redirects]]
from = "http://www.jardinier-paysagiste.org/pages/nos-activites/page.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "https://www.jardinier-paysagiste.org/pages/nos-activites/page.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "http://jardinier-paysagiste.org/contact/contact.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "https://jardinier-paysagiste.org/contact/contact.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "http://www.jardinier-paysagiste.org/pages/nos-activites/desinsectisation.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "https://www.jardinier-paysagiste.org/pages/nos-activites/desinsectisation.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "http://www.jardinier-paysagiste.org/album-photos/ecopiege-chenille-processionnaire-pin.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "https://www.jardinier-paysagiste.org/album-photos/ecopiege-chenille-processionnaire-pin.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "http://www.jardinier-paysagiste.org/album-photos/ecopiege-chenille-processionnaire-pin.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true

[[redirects]]
from = "https://www.jardinier-paysagiste.org/album-photos/ecopiege-chenille-processionnaire-pin.html"
to = "https://jardinier-paysagiste.org/"
status = 301
force = true
